// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YUSkm1m61kha4sv3-5IGESMqmgBQ15M',
    appId: '1:625176176833:web:a247a417bbdb04113d4c40',
    messagingSenderId: '625176176833',
    projectId: 'push-notification-700f0',
    authDomain: 'push-notification-700f0.firebaseapp.com',
    storageBucket: 'push-notification-700f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnw6yUJjd7lPuMEP2-WOA3THj1p7kAIg',
    appId: '1:625176176833:android:6bcf3538385aa8c03d4c40',
    messagingSenderId: '625176176833',
    projectId: 'push-notification-700f0',
    storageBucket: 'push-notification-700f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWA85Szw26rw44D975ER6eyxPlV7BxYrI',
    appId: '1:625176176833:ios:a199f6c1d463e2c03d4c40',
    messagingSenderId: '625176176833',
    projectId: 'push-notification-700f0',
    storageBucket: 'push-notification-700f0.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWA85Szw26rw44D975ER6eyxPlV7BxYrI',
    appId: '1:625176176833:ios:6b5a890d8b8d83853d4c40',
    messagingSenderId: '625176176833',
    projectId: 'push-notification-700f0',
    storageBucket: 'push-notification-700f0.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
